import type { Row } from './api';

export const fieldLabels: Record<string, string> = {
  artifactId: '模型制品编号',
  releaseId: '模型发布编号',
  manifestSha256: '发布清单校验摘要',
  registryVersion: '运行注册版本',
  budgetUsdt: '运行预算 / USDT',
  durationSeconds: '运行时长 / 秒',
  groupId: '策略组编号',
  runId: '运行实例编号',
  instId: '交易品种',
  instIdA: '品种 A',
  instIdB: '品种 B',
  instType: '产品',
  instFamily: '产品系列',
  instCategory: '资产类别',
  ccy: '币种',
  ccyList: '币种',
  baseCcy: '基础币',
  quoteCcy: '计价币',
  settleCcy: '结算币',
  instCcy: '基础币',
  side: '方向',
  sz: '数量',
  px: '价格',
  amt: '金额',
  ordType: '委托类型',
  ordId: '订单号',
  clOrdId: '客户订单号',
  algoId: '策略订单号',
  algoClOrdId: '策略客户订单号',
  algoOrdType: '策略类型',
  tdMode: '交易模式',
  mgnMode: '保证金模式',
  posSide: '持仓方向',
  posMode: '持仓模式',
  posId: '仓位编号',
  reduceOnly: '只减仓',
  lever: '杠杆倍数',
  leverage: '杠杆倍数',
  bar: '周期',
  limit: '条数',
  after: '起始游标',
  before: '结束游标',
  begin: '开始时间',
  end: '结束时间',
  since: '开始时间',
  status: '范围',
  state: '状态',
  type: '类型',
  action: '操作',
  archive: '历史归档',
  history: '历史记录',
  page: '页码',
  from: '转出账户',
  to: '转入账户',
  subAcct: '子账户',
  clientId: '客户编号',
  reqId: '请求编号',
  newPx: '新价格',
  newSz: '新数量',
  newClOrdId: '新客户订单号',
  newTpTriggerPx: '新止盈触发价',
  newTpOrdPx: '新止盈委托价',
  newSlTriggerPx: '新止损触发价',
  newSlOrdPx: '新止损委托价',
  tpTriggerPx: '止盈触发价',
  tpOrdPx: '止盈委托价',
  slTriggerPx: '止损触发价',
  slOrdPx: '止损委托价',
  tpTriggerPxType: '止盈参考价',
  slTriggerPxType: '止损参考价',
  tpOrdKind: '止盈类型',
  triggerPx: '触发价',
  triggerPxType: '触发参考价',
  callbackRatio: '回调比例',
  callbackSpread: '回调价差',
  activePx: '激活价格',
  stpMode: '自成交处理',
  tgtCcy: '数量单位',
  tag: '标签',
  orders: '订单',
  accounts: '账户',
  minPx: '最低价',
  maxPx: '最高价',
  gridNum: '网格数量',
  runType: '网格模式',
  baseSz: '基础币投入',
  quoteSz: '计价币投入',
  basePos: '建仓',
  direction: '方向',
  stopType: '停止方式',
  name: '名称',
  id: '编号',
  productId: '产品编号',
  protocolType: '协议类型',
  term: '期限',
  rate: '年利率',
  earnType: '产品类型',
  keyword: '关键词',
  coins: '币种',
  language: '语言',
  region: '地区',
  importance: '重要程度',
  sentiment: '情绪',
  categories: '分类',
  authorId: '作者',
  authorIds: '作者',
  platform: '平台',
  indicator: '指标',
  params: '指标参数',
  period: '周期',
  timePeriod: '计算周期',
  timeInterval: '时间间隔',
  sortBy: '排序字段',
  sortOrder: '排序',
  timeframe: '时间范围',
  window: '回看窗口',
  minLast: '最低价格',
  maxLast: '最高价格',
  minVolUsd24h: '最低成交额',
  maxVolUsd24h: '最高成交额',
  minChg24hPct: '最低涨跌幅',
  maxChg24hPct: '最高涨跌幅',
  minOiUsd: '最低持仓量',
  maxOiUsd: '最高持仓量',
  minFundingRate: '最低资金费率',
  maxFundingRate: '最高资金费率',
  minMarketCapUsd: '最低市值',
  maxMarketCapUsd: '最高市值',
  minAbsOiDeltaPct: '最小持仓量变化',
  granularity: '粒度',
  ctType: '合约类型',
  uly: '标的指数',
  underlying: '标的资产',
  optType: '期权类型',
  pxLimit: '限价',
  orderPx: '委托价',
  szLimit: '数量上限',
  notionalSz: '名义金额',
  notionalCcy: '名义币种',
  chaseType: '追价方式',
  chaseVal: '追价幅度',
  maxChaseType: '最大追价方式',
  maxChaseVal: '最大追价幅度',
  allowEarlyRedeem: '提前赎回',
  allowReinvest: '自动续投',
  investData: '投入资产',
  reserveFunds: '保留资金',
  initOrdAmt: '首单金额',
  safetyOrdAmt: '补仓金额',
  maxSafetyOrds: '最多补仓次数',
  pxSteps: '补仓价差',
  pxStepsMult: '价差倍数',
  volMult: '补仓倍数',
  tpPct: '止盈比例',
  slPct: '止损比例',
  tpRatio: '止盈比例',
  slRatio: '止损比例',
  slMode: '止损方式',
  eventId: '事件',
  seriesId: '系列',
  outcome: '结果',
  expTime: '到期时间',
  returnList: '返回明细',
  autoCxl: '自动撤单',
  cxlOnClosePos: '平仓时撤单',
  closeFraction: '平仓比例',
  mktClose: '市价平仓',
  tool: '功能',
  level: '等级',
  format: '格式',
  updateTime: '更新时间',
  ts: '时间',
  cashBal: '余额',
  availBal: '可用',
  frozenBal: '冻结',
  fillTime: '成交时间',
  fillPx: '成交价',
  fillSz: '成交数量',
  fee: '手续费',
  feeCcy: '费用币种',
  accFillSz: '累计成交',
  eq: '权益',
  eqUsd: '权益 (USD)',
  upl: '浮动盈亏',
  avgPx: '均价',
  last: '最新价',
  open24h: '24h 开盘',
  high24h: '24h 最高',
  low24h: '24h 最低',
  vol24h: '24h 成交量',
  volCcy24h: '24h 成交额',
  bidPx: '买一价',
  askPx: '卖一价',
  bidSz: '买一数量',
  askSz: '卖一数量',
  at: '时间',
  profile: '账户',
  parameters: '参数',
  result: '结果',
  code: '代码',
  msg: '消息',
  details: '明细',
  data: '数据',
};

const actions: Record<string, string> = {
  get_ticker: '行情',
  get_tickers: '全部行情',
  get_orderbook: '订单簿',
  get_candles: 'K 线',
  get_instruments: '交易品种',
  get_funding_rate: '资金费率',
  get_mark_price: '标记价格',
  get_trades: '最新成交',
  get_index_ticker: '指数行情',
  get_index_candles: '指数 K 线',
  get_price_limit: '价格限制',
  get_open_interest: '持仓量',
  get_stock_tokens: '股票代币',
  get_instruments_by_category: '品种分类',
  filter: '筛选',
  get_oi_history: '持仓量历史',
  filter_oi_change: '持仓量变化',
  get_pair_spread: '品种价差',
  get_indicator: '指标查询',
  list_indicators: '指标列表',
  place_order: '下单',
  cancel_order: '撤单',
  amend_order: '改单',
  get_orders: '委托查询',
  get_order: '订单详情',
  place_algo_order: '创建条件单',
  amend_algo_order: '修改条件单',
  cancel_algo_order: '撤销条件单',
  cancel_algo_orders: '批量撤销条件单',
  get_algo_orders: '条件单查询',
  get_fills: '成交查询',
  batch_orders: '批量委托',
  batch_amend: '批量改单',
  batch_cancel: '批量撤单',
  set_leverage: '设置杠杆',
  get_leverage: '杠杆设置',
  get_positions: '持仓查询',
  close_position: '平仓',
  place_move_stop_order: '移动止损',
  get_greeks: '希腊值',
  get_balance: '交易账户余额',
  transfer: '划转',
  get_max_size: '可交易数量',
  get_asset_balance: '资金账户余额',
  get_bills: '账单',
  get_positions_history: '历史仓位',
  get_trade_fee: '交易费率',
  get_config: '账户设置',
  get_max_withdrawal: '可转出金额',
  get_max_avail_size: '可用数量',
  get_bills_archive: '历史账单',
  set_position_mode: '设置持仓模式',
  get_balance_all: '资产总览',
  browse: '当前事件',
  get_series: '事件系列',
  get_events: '事件列表',
  get_markets: '事件市场',
  get_latest: '最新资讯',
  get_by_coin: '币种资讯',
  search: '搜索',
  get_detail: '资讯详情',
  get_coin_sentiment: '币种情绪',
  get_sentiment_ranking: '情绪排行',
  get_economic_calendar: '财经日历',
  get_domains: '资讯来源',
  list_calendar_regions: '地区',
  get_order_details: '策略详情',
  get_sub_orders: '子订单',
  create_order: '创建策略',
  stop_order: '停止策略',
  get_liquidate_price: '预估强平价',
  get_savings_balance: '活期持仓',
  get_fixed_order_list: '定期持仓',
  savings_purchase: '申购',
  savings_redeem: '赎回',
  set_lending_rate: '设置利率',
  get_lending_history: '收益记录',
  fixed_purchase: '定期申购',
  fixed_redeem: '定期赎回',
  get_lending_rate_history: '利率历史',
  get_fixed_earn_products: '定期产品',
  auto_set: '自动赚币',
  get_flash_earn_projects: '闪赚',
  earn_get_offers: '产品列表',
  earn_purchase: '申购',
  earn_redeem: '赎回',
  earn_cancel: '取消申购',
  earn_get_active_orders: '当前持仓',
  earn_get_order_history: '历史订单',
  get_currency_pairs: '投资币对',
  get_products: '产品列表',
  get_order_state: '订单状态',
  subscribe: '申购',
  redeem: '赎回',
  get_traders_by_filter: '交易员排行',
  get_performance_by_trader: '收益表现',
  get_trader_positions: '当前持仓',
  get_trader_positions_history: '历史持仓',
  get_trader_orders_history: '历史委托',
  search_trader: '搜索交易员',
  get_signal_overview_by_filter: '信号筛选',
  get_signal_overview_by_trader: '交易员信号',
  get_signal_trend_by_filter: '信号趋势',
  get_signal_trend_by_trader: '交易员趋势',
  get_history: '操作历史',
  get_categories: '分类',
  download: '安装',
  get_capabilities: '服务能力',
};
const restTitles: Record<string, string> = {
  'Adjust demo account balance': '调整测试账户余额',
  'Cancel withdrawal order': '撤销提款',
  'Create withdrawal order': '提款',
  'Get deposit order detail': '充值详情',
  'Get deposit order history': '充值记录',
  'Get deposit payment methods': '充值方式',
  'Get withdrawal order detail': '提款详情',
  'Get withdrawal order history': '提款记录',
  'Get withdrawal payment methods': '提款方式',
  'E-Mode info': '高效模式',
  'Get OKUSD Account': 'OKUSD 账户',
  'Get APR History': '年利率历史',
  'Redeem OKUSD': '赎回 OKUSD',
  'Get Redemption History': '赎回记录',
  'Get Rewards History': '收益记录',
  'Subscribe OKUSD': '申购 OKUSD',
  'Get Subscription History': '申购记录',
  'Saving balance': '活期余额',
  'Lending history': '出借记录',
  'Public borrow history (public)': '市场借贷历史',
  'Public borrow info (public)': '市场借贷数据',
  'Savings purchase/redemption': '申购与赎回',
  'Set lending rate': '设置利率',
  'Cancel purchases/redemptions': '取消申购与赎回',
  Offers: '产品列表',
  'Active orders': '当前订单',
  'Order history': '历史订单',
  Purchase: '申购',
  Redeem: '赎回',
  'SBE Order book': 'SBE 订单簿',
  'Get instrument tick bands': '价格精度',
  'Get security fund': '保险基金',
  Status: '服务状态',
  'Amend spot dca basic param': '修改策略参数',
  'Add dca margin': '增加保证金',
  'Reduce dca margin': '减少保证金',
  'DCA algo order details': '策略详情',
  'Add investment': '追加投入',
  'Get / DCA algo order position details': '策略持仓',
  'Amend dca reinvestment': '修改复投设置',
  'Amend dca take profit settings': '修改止盈',
  'Stop dca algo order': '停止策略',
  'Amend grid algo order basic param': '修改网格参数',
  'Amend recurring buy amount': '修改定投金额',
  'Amend recurring buy time': '修改定投时间',
  'Pause recurring buy': '暂停定投',
  'Restart recurring buy': '恢复定投',
  'Signal bot history': '信号策略历史',
  'Get GLP historical performance': 'GLP 历史表现',
  'Get GLP today performance': 'GLP 当日表现',
};
export function operationLabel(item: Row): string {
  if (item.kind === 'model_release')
    return (
      (
        {
          validate: '校验模型',
          publish: '发布模型',
          rollback: '回退模型发布',
        } as Record<string, string>
      )[item.name] || item.name
    );
  if (item.kind === 'group')
    return (
      (
        {
          start: '开始运行',
          halt: '暂停开仓',
          reduce: '仅减仓',
          resume: '恢复运行',
          stop: '停止运行',
          cancel: '撤单并暂停',
          flatten: '平仓',
        } as Row
      )[item.name] || item.name
    );
  if (item.kind === 'native')
    return (
      (
        {
          status: '运行状态',
          positions: '持仓',
          orders: '委托',
          fills: '成交',
          strategies: '策略',
          config: '参数',
          exceptions: '异常',
          stop: '停止运行',
        } as Row
      )[item.name] || item.name
    );
  if (item.kind === 'profile')
    return (
      (
        {
          save: '保存 API 连接',
          select: '切换账户',
          delete: '删除 API 连接',
        } as Row
      )[item.name] || item.name
    );
  if (item.kind === 'rest' || item.path) {
    const title = item.displayTitle || item.title || item.name;
    if (title === 'Stable Rewards')
      return /quote$/.test(item.path)
        ? '稳定收益报价'
        : /history$/.test(item.path)
          ? '稳定收益记录'
          : '稳定收益申赎';
    return restTitles[title] || title;
  }
  return (
    actions[item.name.slice(item.name.indexOf('_') + 1)] ||
    item.title ||
    item.name
  );
}
export const valueLabels: Record<string, string> = {
  buy: '买入',
  sell: '卖出',
  limit: '限价',
  market: '市价',
  cash: '现货',
  cross: '全仓',
  isolated: '逐仓',
  SPOT: '现货',
  SWAP: '永续',
  FUTURES: '交割',
  OPTION: '期权',
  MARGIN: '杠杆',
  open: '当前',
  live: '当前',
  history: '历史',
  archive: '历史归档',
  conditional: '条件单',
  oco: '止盈止损',
  move_order_stop: '移动止损',
  post_only: '只做 Maker',
  net: '单向',
  long: '多头',
  short: '空头',
  base_ccy: '基础币',
  quote_ccy: '计价币',
  completed: '已返回',
  processing: '处理中',
  error: '失败',
  unknown: '待核对',
  partially_filled: '部分成交',
  filled: '已成交',
  canceled: '已撤销',
  ACTIVE: '运行中',
  HALTED: '已停止',
};
export const fieldLabel = (key: string, schema?: Row): string =>
  fieldLabels[key] || schema?.title || key;
export const valueLabel = (value: unknown): string =>
  valueLabels[String(value)] || String(value ?? '—');
